<div class="page__base" data-remote="true" data-route="^(?:\/home|\/index\.php|\/$)(?:\/)?(.*)$"></div>
<div class="page__base" data-remote="true" data-route="^\/projects\/ourproduct\/?(.*)$"></div>
<div class="page__base" data-remote="true" data-route="^\/projects\/researchpaper\/?(.*)$"></div>
<div class="viewing page__base" data-route="^\/projects\/outreach\/?(.*)$">Outreach</div>
<div class="page__base" data-remote="true" data-route="^\/projects\/game\/?(.*)$"></div>
<div class="page__base" data-remote="true" data-route="^\/ourcompany\/boardofdirectors\/?(.*)$"></div>
<div class="page__base" data-remote="true" data-route="^\/ourcompany\/roboticsdivision\/?(.*)$"></div>
<div class="page__base" data-remote="true" data-route="^\/ourcompany\/notebookdivision\/?(.*)$"></div>
<div class="page__base" data-remote="true" data-route="^\/ourcompany\/displaydivision\/?(.*)$"></div>
<div class="page__base" data-remote="true" data-route="^\/ourcompany\/mediadivision\/?(.*)$"></div>
<div class="page__base" data-remote="true" data-route="^\/ourcompany\/marketingdivision\/?(.*)$"></div>
<div class="page__base" data-remote="true" data-route="^\/sponsors\/?(.*)$"></div>
<div class="page__base" data-remote="true" data-route="^\/contactus\/?(.*)$"></div>
<div class="page__base" data-remote="true" data-route="^\/ourcompany\/spirit\/?(.*)$"></div>